/*
    Generated by Atomist on 04 07 2016 
*/
package treehorn;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
* Spring Java configuration file for BlankTemplate.
* Don't even think of using XML.
*/
@Configuration
public class BlankTemplateConfiguration {

    // Your beans go here ... 
	// Atomist Bot suggests "maybe use an Atomist project editor to add a sample one?"
}
