/*
    Generated by Atomist on 04 07 2016 
*/
package treehorn;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class BlankTemplateApplication {

    public static void main(String[] args) {
        SpringApplication.run(BlankTemplateApplication.class, args);
    }
}
