/*
    Generated by Atomist on 04 07 2016 
*/
package treehorn;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = BlankTemplateApplication.class)
@WebAppConfiguration
public class BlankTemplateApplicationTests {

	@Test
	public void contextLoads() {
	}
}
